package hello;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.Lesson;
import hello.LessonRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/course") // This means URL's start with /course (after Application path)
public class MainController {
	@Autowired // This means to get the bean called lessonRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private LessonRepository lessonRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addLesson (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Lesson n = new Lesson();
		n.setName(name);
		lessonRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Lesson> getAllLessons() {
		// This returns a JSON or XML with the lessons
		return lessonRepository.findAll();
	}
	
	@GetMapping(path="/show")
	public @ResponseBody Optional<Lesson> showLesson(@RequestParam Long id) {
		// This returns a JSON or XML with the lessons
		return lessonRepository.findById(id);
	}
	
	@GetMapping(path="/delete")
	public @ResponseBody String deleteLesson(@RequestParam Long id) {
		// This returns a JSON or XML with the lessons
		lessonRepository.deleteById(id);
		return "Deleted";
	}
}